spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/clinic_management
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=clinic_management_super_secret_key_2026_for_jwt_authentication
jwt.expiration=86400000

payment.momo.partner-code=MOMO
payment.momo.access-key=F8BBA842ECF85
payment.momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz
payment.momo.create-endpoint=https://test-payment.momo.vn/v2/gateway/api/create
payment.momo.redirect-url=http://localhost:8080/api/payments/momo/return
payment.momo.ipn-url=http://localhost:8080/api/payments/momo/ipn
payment.momo.frontend-result-url=http://localhost:5173/payment/momo-result
payment.momo.request-type=payWithATM
payment.momo.lang=vi
payment.momo.store-name=ClinicMS
payment.momo.store-id=ClinicMS
